### ISSUE TITLE
[Bug]: No Data on Grafana

### ISSUE THREAD

**Issue by ediziks** [kamontat/fthelper#57]
### Module

fthelper

### Version

v5.0.0-beta.12

### What happened?

Probably it's not a bug but some configuration faults by my side. Tried to follow the [blog post](https://blog.kamontat.net/posts/setup-freqtrade-with-grafana#complete-docker-compose), not sure if it's still valid with latest version though. The issue must be on prometheus, simply a 'no data' issue. freqtrade itself, freqUI, grafana and ftmetric works as expected but the prometheus. on grafana, data source is added and approved, no any extraordinary errors under `docker-compose logs` but `unhealthy` tag on freqtrade's container.

### Docker compose configuration

```yml
version: "3"

volumes:
  grafana-data:
  prometheus-data:

services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop_plot
    container_name: freqtrade
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
        --logfile "/freqtrade/user_data/logs/freqtrade.log"
        --config "/freqtrade/user_data/config.json"
        --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
        --strategy BB_RPB_TSL_RNG_TBS_stashtra
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config-rest.json version | grep -q version"]
      interval: 30s
      timeout: 4s
      retries: 3
#      start_period: 1m
  # single mode
  ftmetric:
    image: ghcr.io/kamontat/ftmetric:v5.0.0-beta.12
    container_name: ftmetric
    restart: on-failure
    environment:
      - FTH_INTERNAL__LOG__LEVEL=3 # 0=silent, 1=error, 2=warn, 3=info, 4=debug

      - FTH_FREQTRADE__HTTP__ENABLED=true
      - FTH_FREQTRADE__HTTP__URL=http://freqtrade:8081
      - FTH_FREQTRADE__HTTP__USERNAME=Freqtrader
      - FTH_FREQTRADE__HTTP__PASSWORD=SuperSecurePassword

      - FTH_FREQTRADE__DB__ENABLED=false
      - FTH_FREQTRADE__DB__TYPE=postgres
      - FTH_FREQTRADE__DB__URL=postgres:5432
      - FTH_FREQTRADE__DB__USERNAME=freqtrade
      - FTH_FREQTRADE__DB__NAME=database_name
      - FTH_FREQTRADE__DB__PASSWORD=password

      - FTH_SERVER__PORT=8090
    depends_on:
      - freqtrade
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/healthcheck"]
      interval: 20s
      timeout: 1s
      retries: 3
#      start_period: 20s
  # cluster mode
  #ftmetricct:
  #  image: ghcr.io/kamontat/ftmetric:v5.0.0-beta.12
  #  container_name: ftmetricct
  #  restart: on-failure
  #  environment:
  #    - FTH_INTERNAL__LOG__LEVEL=3 # enabled info log
  #    - FTH_CLUSTERS=1A,2A

  #    - FTC_1A__FREQTRADE__HTTP__ENABLED=true
  #    - FTC_1A__FREQTRADE__HTTP__URL=http://freqtrade:8080
  #    - FTC_1A__FREQTRADE__HTTP__USERNAME=freqtrade
  #    - FTC_1A__FREQTRADE__HTTP__PASSWORD=password
  #    - FTC_1A__FREQTRADE__DB__ENABLED=false
  #    - FTC_1A__FREQTRADE__DB__TYPE=postgres
  #    - FTC_1A__FREQTRADE__DB__URL="localhost:5432"
  #    - FTC_1A__FREQTRADE__DB__NAME="freqtrade"
  #    - FTC_1A__FREQTRADE__DB__USERNAME="freqtrade"
  #    - FTC_1A__FREQTRADE__DB__PASSWORD="password"

  #    - FTC_2A__FREQTRADE__HTTP__ENABLED=true
  #    - FTC_2A__FREQTRADE__HTTP__URL="http://localhost:8081"
  #    - FTC_2A__FREQTRADE__HTTP__USERNAME="freqtrade"
  #    - FTC_2A__FREQTRADE__HTTP__PASSWORD="password"
  #    - FTC_2A__FREQTRADE__DB__ENABLED=false

  #    - FTH_SERVER__PORT=8090
  prometheus:
    image: prom/prometheus:v2.28.0
    restart: on-failure
    # be aware before open the port
    ports:
      - 9090:9090
    volumes:
      # TODO: add configuration at prometheus/prometheus.yml
      - ./prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 1m
      timeout: 1s
      retries: 3
#      start_period: 15s
  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - freqtrade
      - prometheus
    volumes:
      - prometheus-data:/prometheus
    environment:
      ## override server url
      # - GF_SERVER_ROOT_URL=http://example.com
      - GF_SERVER_HTTP_PORT=3000
      ## enabled grafana beta alert manager
      # - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=verygrafanapassword
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 1m
      timeout: 1s
      retries: 3
#      start_period: 15s
```
